import Link from "next/link";
import { SiteFooter } from "./site-footer";
import { SiteHeader } from "./site-header";

const pilotFacts = [["03","episodes"],["257 s","interaction time"],["01","cotton T-shirt"],["03","regions"],["RGB","fixed top-down"],["24 fps","848 × 478"],["10 cm","visual reference"]] as const;
const plannedDatasets = [["02","Folding"],["03","Laundry handling"],["04","Hanging"],["05","Sorting"],["06","Packing"]] as const;
const collectionSteps = ["Human demonstration","Controlled capture","Structured metadata","Annotation","Dataset"] as const;
const currentFormat = [["RGB video","MP4"],["Episode metadata","CSV"],["Calibration reference","JPG / MP4"],["Documentation","schema · protocol · dataset card"]] as const;
const waysToWork = [
  {tier:"Free",name:"Explore",price:"$0",purpose:"Evaluate whether the current data is relevant.",details:"Selected sample episodes, episode metadata, schema, dataset card and collection protocol.",cta:"Explore sample",href:"/dataset"},
  {tier:"Scoped",name:"Extend",price:"Custom quote",purpose:"Extend an existing dataset along specific variation axes.",details:"Garment type, material, region, starting configuration, operator, capture condition or annotation depth.",cta:"Scope an extension",href:"#request-data"},
  {tier:"Custom",name:"Capture",price:"Talk to us",purpose:"Define and collect a manipulation behavior not yet in the catalogue.",details:"Task → behavior definition → variation grid → capture → annotation → delivery.",cta:"Brief a task",href:"#request-data"},
] as const;
function Arrow(){return <span aria-hidden="true">↗</span>}

export default function Home(){return <main id="top">
  <SiteHeader />
  <section className="homeHero" aria-labelledby="hero-title"><div className="heroCopy"><p className="labNote">REAL-WORLD DATA / PHYSICAL AI</p><p className="heroBrand">nAIve physics</p><h1 id="hero-title">Real-world garment manipulation datasets <em>for Physical AI.</em></h1><p className="heroLead">Human demonstrations of textile manipulation, structured for robotics and embodied intelligence.</p><div className="heroActions"><Link className="button buttonRed" href="/dataset">Explore datasets <Arrow/></Link><a className="button buttonLine" href="#collection">How we collect</a></div></div><div className="experimentSheet" aria-label="Textile manipulation research diagram"><div className="sheetTop"><span>CATALOGUE / 001</span><span>PILOT / 2026</span></div><div className="clothDiagram" aria-hidden="true"><span className="clothNeck"/><span className="clothBody"/><span className="measure measureX">deformable geometry</span><span className="measure measureY">contact + tension</span></div><div className="sheetNotes"><span>RGB / 24 FPS</span><span>TOP-DOWN / FIXED</span><span>GRID / 10 CM</span></div><p className="handNote">observe the physical interaction through time</p></div></section>

  <section className="homeSection problemSection" aria-labelledby="problem-title"><div className="sectionMarker"><span>01</span><p>The problem</p></div><div className="problemCopy"><h2 id="problem-title">Fabric is deformable.</h2><p>Its geometry changes continuously through contact, tension, gravity and tool interaction. Robots therefore need data describing how humans physically manipulate textiles through time.</p></div><div className="problemTerms">{["changing geometry","contact","tension","gravity","tool interaction"].map((term,index)=><span key={term}><b>{String(index+1).padStart(2,"0")}</b>{term}</span>)}</div></section>

  <section className="homeSection catalogueSection" id="categories" aria-labelledby="catalogue-title"><div className="sectionMarker"><span>02</span><p>Dataset catalogue</p></div><div className="catalogueIntro"><p className="labNote">CATEGORY / GARMENT MANIPULATION</p><h2 id="catalogue-title">A catalogue of physical textile behaviors.</h2></div><article className="availableDataset"><div><span>01 / AVAILABLE</span><strong>Ironing</strong><small>Ironing v0.1 · Pilot</small></div><div className="factLedger">{pilotFacts.map(([value,label])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><Link className="button buttonPaper" href="/dataset">Explore dataset <Arrow/></Link></article><div className="plannedCatalogue" aria-label="Planned datasets">{plannedDatasets.map(([number,name])=><article key={number}><span>{number}</span><strong>{name}</strong><small>Planned / not currently available</small></article>)}</div><div className="roadmapNote"><p>Future industrial textile manipulation may include fabric alignment, feeding, stacking, sewing preparation and inspection.</p><strong>ROADMAP / NOT CURRENT DATASETS</strong></div></section>

  <section className="homeSection collectionSection" id="collection" aria-labelledby="collection-title"><div className="sectionMarker"><span>03</span><p>How we collect</p></div><div className="whiteboard"><div className="whiteboardHeading"><p className="labNote">CURRENT PROTOCOL / IRONING v0.1</p><h2 id="collection-title">Human action becomes a structured research record.</h2></div><ol>{collectionSteps.map((step,index)=><li key={step}><span>{String(index+1).padStart(2,"0")}</span><strong>{step}</strong></li>)}</ol><div className="protocolFacts"><span>indoor capture</span><span>fixed ironing surface</span><span>single smartphone</span><span>approximately top-down</span><span>episode-level metadata</span></div><p className="protocolCaveat">The 10 cm grid is a visual spatial reference only. It is not full intrinsic or extrinsic camera calibration.</p></div></section>

  <section className="homeSection formatSection" id="data-format" aria-labelledby="format-title"><div className="sectionMarker"><span>04</span><p>Data format</p></div><div className="formatCopy"><h2 id="format-title">Know exactly what you receive.</h2><p>The current pilot combines RGB observations with episode identity, garment, task, action, capture configuration and media properties.</p></div><div className="formatEquation">{currentFormat.map(([name,type],index)=><div key={name}><span>{String(index+1).padStart(2,"0")}</span><strong>{name}</strong><small>{type}</small></div>)}</div><p className="notIncludedNote"><strong>Not currently included:</strong> LeRobot, RLDS, HDF5, depth, force/tactile, hand pose, 6-DoF trajectories, robot state/action vectors or frame-level segmentation.</p></section>

  <section className="homeSection freeToolSection" aria-labelledby="free-tool-title"><div className="sectionMarker"><span>05</span><p>Free tool</p></div><div className="freeToolIntro"><p className="labNote">FREE TOOL / DATA WORKBENCH</p><h2 id="free-tool-title">Turn manipulation video into structured training data.</h2><p>Upload a local RGB video, mark manipulation behaviors, derive frame ranges and export machine-readable annotations.</p><Link className="button buttonRed" href="/annotate">Open Free Annotation Tool <Arrow/></Link></div><ul className="freeToolCapabilities">{["local video upload","temporal behavior segmentation","frame-addressable labels","timeline inspection","CSV export","provenance-aware annotations"].map((capability)=><li key={capability}>{capability}</li>)}</ul><p className="freeToolNote">Videos selected in the current version are processed locally in the browser for annotation and are not automatically added to the nAIve physics commercial dataset.</p></section>

  <section className="homeSection pricingSection" id="pricing" aria-labelledby="pricing-title"><div className="sectionMarker"><span>06</span><p>Ways to work</p></div><div className="pricingIntro"><h2 id="pricing-title">Explore, extend or define a new behavior.</h2><p>Commercial licensing is available. Usage, ownership, exclusivity and redistribution terms are defined in the applicable dataset agreement.</p></div><div className="pricingGrid">{waysToWork.map(item=><article key={item.name}><p>{item.tier}</p><h3>{item.name}</h3><strong>{item.price}</strong><p>{item.purpose}</p><small>{item.details}</small><Link href={item.href}>{item.cta} <Arrow/></Link></article>)}</div><blockquote>“We need the ironing dataset with formal shirts, linen and collars.”<span>Example scoped request</span></blockquote></section>

  <section className="homeSection aboutSection" id="about" aria-labelledby="about-title"><div className="sectionMarker"><span>07</span><p>About</p></div><div><h2 id="about-title">Curious about how physical intelligence learns.</h2><p>nAIve physics is exploring how high-quality real-world human manipulation data can accelerate Physical AI research.</p></div><div id="request-data" className="requestPanel"><span>REQUEST DATA / BUILD WEEK</span><strong>Need a behavior or variation that is not in the pilot?</strong><a href="#pricing">Choose a collection path →</a></div></section>
  <SiteFooter/>
</main>}
